### ISSUE TITLE
jump to another page in the same site, "Title" does not change until refreshing

### ISSUE THREAD

**Issue by joshatt** [osmoscraft/osmosmemo-template#1]
This is in youtube site, after I save a page (with chrome extension) then jump to another one then try to save it, "link" changes correspondingly but "title" does not, I have to refresh the page and save again.

**Comment by chuanqisun** [comment]
Thanks @joshatt. I've noticed the behavior too. I've filed complaints with YouTube on how they incorrectly used a stale title in html when people move from one page to another but I doubt they will listen to us independent developers. So my current plan is to add some special case handling logic. There is already an issue I'm using for tracking the work. Thanks for the patience!

Closed in favor of:
https://github.com/osmoscraft/osmosmemo/issues/8
